# Generated by Django 3.1.7 on 2021-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='logo_deafult.png', null=True, upload_to='company_images',
                                    verbose_name='Логотип'),
        ),
    ]
